

name: Build Binaries
run-name: '[${{ github.event_name }}] ${{ github.ref_name }}'

# When is the workflow actually triggerd
on:
  # Manually triggered
  workflow_dispatch:
  push:
    branches:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
    paths-ignore:
      - 'docs/**'
      - '*.md'

  #TODO: Once 'main' is replaced
  # schedule:
  #   # Every Wednesday at midnight
  #   - cron:  '0 0 * * 3'

# Full concurrent
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Develop build only for weekly build
env:
  debug: ${{ (github.event_name == 'schedule') && 'debug' || 'release' }}

jobs:
  # Scan the working directory to trigger build based on
  # the latest change that have been made to the repo
  paths-filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          ref: ${{ github.ref }}
          filters: |
            qemu:
              - 'qemu/**'
              - 'build'
            flexus:
              - 'flexus/**'
              - 'build'
    outputs:
      qemu: ${{ steps.changes.outputs.qemu }}
      flexus: ${{ steps.changes.outputs.flexus }}

  # Build the Kraken if their files have been modified
  build_simulator:
    name: Build Simulators
    needs: paths-filter
    if: ${{ (needs.paths-filter.outputs.flexus == 'true') || github.event_name == 'schedule' }}
    env:
      CC: gcc-13
      CXX: g++-13


    strategy:
      fail-fast: false
      matrix:
        binaries:
          - keenkraken
          - knottykraken

    runs-on: ubuntu-latest
    steps:
      - name: Checkout QFlex
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'

      - name: Install conan
        run: pip install conan

      - name: Detect current environmment profile
        run: conan profile detect --force

      - name: Build
        run: ./build ${{ matrix.binaries }} ${{ env.debug }}

  # Build QEMU only
  build_qemu:
    name: Build Qemu
    needs: paths-filter
    if: ${{ (needs.paths-filter.outputs.qemu == 'true') || github.event_name == 'schedule' }}

    runs-on: ubuntu-latest
    container:
      image: birate/qflex-builder:2024.04

    steps:
      - name: Checkout QFlex
        uses: actions/checkout@v4
        with:
          submodules: true

      # Special checkout for QEMU (yet)
      - name: Checkout libqflex
        uses: actions/checkout@v4
        with:
          repository: parsa-epfl/libqflex
          ref: feat/qemu-8.2
          path: qemu/middleware

      - name: Build
        run: ./build qemu ${{ env.debug }}